#!/usr/bin/env python3
"""
Generate the 5 dashboard 1-bit icon header files (32px + 64px each) from
Bootstrap Icons SVG sources.

This is a one-shot scratch tool. Re-run when you want to swap glyph
choices: edit ICON_MAP, re-run, commit the regenerated `.h` files.

Usage:
  DYLD_LIBRARY_PATH=$(brew --prefix cairo)/lib \
    python3 scripts/scratch/build_dashboard_icons.py

Outputs:
  src/components/icons/<name>.h     (32x32, *Icon symbol)
  src/components/icons/<name>64.h   (64x64, *64Icon symbol)
"""
from __future__ import annotations

import io
import os
import sys

import cairosvg  # type: ignore
from PIL import Image  # type: ignore


HERE = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
SVG_ROOT = os.path.join(HERE, "bootstrap-icons-1.11.3")
OUT_DIR = os.path.join(REPO_ROOT, "src", "components", "icons")

# (output_name, source_svg_basename, symbol_prefix_for_C_var)
# C variable becomes "<symbol_prefix>Icon" / "<symbol_prefix>64Icon"
ICON_MAP = [
    ("weather", "cloud-sun", "Weather"),
    ("calendar", "calendar3", "Calendar"),
    ("bookmark", "bookmark", "Bookmark"),
    ("joystick", "controller", "Joystick"),
    ("appgrid", "grid-3x3-gap", "AppGrid"),
]


def render_svg_to_1bit(svg_path: str, size_px: int) -> bytes:
    """Rasterize SVG → 1-bit packed bytes (top-down, MSB-first, byte-padded
    rows) AS THE PANEL SEES THEM (physical landscape orientation).

    drawIcon(bitmap, x, y, w, h) calls display.drawImageTransparent(bitmap, y,
    panelW - w - x, h, w) — i.e. it writes the byte stream row-major in the
    panel's PHYSICAL 800x480 landscape orientation, then the firmware's
    GfxRenderer rotation makes the user see it upright on the logical-
    portrait 480x800 display.

    Therefore an icon authored for the user's view (upright) must be stored
    rotated 90° CCW so that the panel's row-major layout, after the
    firmware's 90° CW rotation, presents it upright to the user. Existing
    icons like book.h follow this convention (their row-major dump shows a
    book lying on its side; on the device it stands upright).
    """
    png_bytes = cairosvg.svg2png(
        url=svg_path,
        output_width=size_px,
        output_height=size_px,
    )
    img = Image.open(io.BytesIO(png_bytes)).convert("LA")
    # Rotate 90° CCW so the byte layout matches the panel orientation.
    img = img.transpose(Image.ROTATE_90)
    pixels = img.load()
    bw = Image.new("1", (size_px, size_px), 1)  # 1 = white
    bw_pixels = bw.load()
    for y in range(size_px):
        for x in range(size_px):
            l, a = pixels[x, y]
            on = a > 64 and l < 224
            # Convention: 1 bit = white background, 0 bit = drawn (black).
            bw_pixels[x, y] = 0 if on else 1
    out = bytearray()
    for y in range(size_px):
        for byte_x in range(size_px // 8):
            byte_value = 0
            for bit in range(8):
                px = bw_pixels[byte_x * 8 + bit, y]
                if px != 0:
                    byte_value |= 1 << (7 - bit)
            out.append(byte_value)
    return bytes(out)


def write_header(out_path: str, var_name: str, size_px: int, data: bytes) -> None:
    rows = []
    bytes_per_row = size_px // 8
    for row_idx in range(size_px):
        start = row_idx * bytes_per_row
        end = start + bytes_per_row
        row_bytes = data[start:end]
        rows.append(", ".join(f"0x{b:02X}" for b in row_bytes))
    body = ",\n    ".join(rows)
    text = (
        "#pragma once\n"
        "#include <cstdint>\n\n"
        f"// size: {size_px}x{size_px}\n"
        f"// auto-generated by scripts/scratch/build_dashboard_icons.py\n"
        f"static const uint8_t {var_name}[] = {{\n"
        f"    {body}\n"
        "};\n"
    )
    with open(out_path, "w") as fh:
        fh.write(text)


def main() -> int:
    if not os.path.isdir(SVG_ROOT):
        print(f"missing: {SVG_ROOT}", file=sys.stderr)
        return 1
    os.makedirs(OUT_DIR, exist_ok=True)

    written = []
    for out_name, svg_base, sym_prefix in ICON_MAP:
        svg_path = os.path.join(SVG_ROOT, f"{svg_base}.svg")
        if not os.path.exists(svg_path):
            print(f"missing svg: {svg_path}", file=sys.stderr)
            return 2

        for size_px, suffix, var_suffix in ((32, "", ""), (64, "64", "64")):
            data = render_svg_to_1bit(svg_path, size_px)
            out_path = os.path.join(OUT_DIR, f"{out_name}{suffix}.h")
            var_name = f"{sym_prefix}{var_suffix}Icon"
            write_header(out_path, var_name, size_px, data)
            written.append(out_path)
            print(f"  {var_name}: {size_px}x{size_px} -> {out_path}")

    print(f"\nWrote {len(written)} header files.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
